### ISSUE TITLE
faulty URL for bitcoin core builder keys 

### ISSUE THREAD

**Issue by jorishr** [BenWestgate/bitcoin-core-on-tails#5]
- Describe the issue
The  URL on line 533 in the [init script](https://github.com/BenWestgate/bitcoin-core-on-tails/blob/master/init) returns 404 not found. 

- Possible solution
Changing the URL to https://github.com/bitcoin/bitcoin/blob/master/contrib/verify-commits/trusted-keys seems to solve the issue. Verification success message is displayed and installation proceeds as expected. 

- To do
I'm not familiar with the bitcoin core repo, so I took a guess to which are the correct builder keys. 
Confirm the correct link and update the .init file.

**Comment by BenWestgate** [comment]
Root cause:
The bitcoin core repository has deleted the contrib/builder-keys/keys.txt file
https://github.com/bitcoin/bitcoin/pull/26598

Even the bitcoincore.org instructions for verification are still out of date due to this:
https://bitcoincore.org/en/download/

Comment on possible solution:
Your file is for commits to the Bitcoin repo rather than the larger list of people who have built and signed releases, there's only 6 trusted keys for commits while a dozen have signed v24.0.1 release, and the old builder-keys/keys.txt file had 50+ individuals.

I have removed cross checking signatures against github in the successor for Tails 5.8+ https://github.com/Bails

I'll leave it to the paranoid user to find sources on their own to confirm the fingerprint displayed belongs to the signer they are considering trusting.

They do still have a list but it's a on a release by release basis. And it was incomplete as of last week.

When bitcoincore.org gives an update I will have Bails follow their newest verification instructions.

I will use your proposed solution in this repository since it's easier than removing it like I did in Bails/bin/bails.
